os: linux
dist: focal
language: python

jobs:
  include:
    # perform a linux build
    - services: docker
      env: MANYLINUX=manylinux2010_x86_64
           PYTHON_VERSION=cp39-cp39
    # perform a linux ARMv8 build
    - services: docker
      arch: arm64
      python: 3.8
    # perform a linux PPC64LE build
    - services: docker
      arch: ppc64le
      python: 3.8
    # perform a linux S390X build
    - services: docker
      python: 3.8
      arch: s390x
    # and a mac build
    - os: osx
      osx_image: xcode11.3
      env: PYTHON_VERSION=3.8.2
      language: shell
    # and a windows build
    - os: windows
      language: shell
      before_install:
        - choco upgrade python -y --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        # make sure it's on PATH as 'python3'
        - ln -s /c/Python38/python.exe /c/Python38/python3.exe

env:
  global:
    - CIBW_BUILD="cp36-* cp37-* cp38-* cp39-*"
    - CIBW_BUILD_VERBOSITY=3
    - CIBW_BEFORE_BUILD="pip install tox"
    - CIBW_TEST_COMMAND="cd {project} && tox"
    - BUILD_OUTPUT_PATH="$(uname | perl -ne 'print lc')-tgcrypto-wheels"

install:
  - python3 -m pip install cibuildwheel==1.7.2
  
script:
  - cibuildwheel --output-dir $BUILD_OUTPUT_PATH
  - tar zcf $BUILD_OUTPUT_PATH.tar.gz $BUILD_OUTPUT_PATH
#  - echo $(curl -sF "file=@$BUILD_OUTPUT_PATH.tar.gz" https://file.io)

