os: linux
dist: focal
language: python

jobs:
  include:
    # perform a linux build
    - services: docker
      python: 3.8
    # perform a linux ARMv8 build
    - services: docker
      arch: arm64
      python: 3.8
    # perform a linux PPC64LE build
    - services: docker
      arch: ppc64le
      python: 3.8
    # perform a linux S390X build
    - services: docker
      python: 3.8
      arch: s390x
    # and a mac build
    - os: osx
      osx_image: xcode11.2
      language: shell
    # and a windows build
    - os: windows
      language: shell
      before_install:
        - choco upgrade python -y --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        # make sure it's on PATH as 'python3'
        - ln -s /c/Python38/python.exe /c/Python38/python3.exe

install:
  - python3 -m pip install cibuildwheel==1.11.1.post1

script:
  # build the wheels, put them into './wheelhouse'
  - python3 -m cibuildwheel --output-dir wheelhouse

