image: python:3.7.2

pipelines:
  default:
    - step:
        name: 'Install stuff'
        deployment: test
        script:  
          - python3 -m pip install wheel 
          - python3 -m pip install -U cibuildwheel
          - python3 -m pip install -U setuptools
          - python setup.py sdist bdist_wheel
    - step:
        name: 'Build wheels'
        script:
          - echo "Yay"

