image: ubuntu

pipelines:
  default:
    - step:
        name: 'Install stuff'
        deployment: test
        script: 
          - uname -a
          - apt-get update
          - DEBIAN_FRONTEND=noninteractive
          - apt-get install -y tzdata
          - apt-get install build-essential -y --force-yes
          - gcc --version
          - apt-get install git cmake -y --force-yes
          - cmake --version
          - apt-get update -y
          - apt-get install -y python3
          - apt-get install -y python3-pip
          - python3 -m pip install wheel 
          - python3 -m pip install -U cibuildwheel
          - python3 -m pip install -U setuptools
          - python3 setup.py sdist bdist_wheel
    - step:
        name: 'Build wheels'
        script:
          - echo "Yay"

