image: ubuntu

pipelines:
  default:
    - step:
        name: 'Install stuff'
        deployment: test
        script:  
          - python3 -m pip install -U cibuildwheel
          - python3 -m pip install -U setuptools
    - step:
        name: 'Build wheels'
        script:
          - echo "Yay"

