image: ubuntu

pipelines:
  default:
    - step:
        name: 'Install stuff'
        deployment: test
        script:  
          - apt-get update -y
          - apt-get install -y python3
          - apt-get install -y python3-pip
          - python3 -m pip install wheel 
          - python3 -m pip install -U cibuildwheel
          - python3 -m pip install -U setuptools
          - python setup.py sdist bdist_wheel
    - step:
        name: 'Build wheels'
        script:
          - echo "Yay"

