name: build package

on: [push]


jobs:
  build_sdist:
    name: Build source dist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies
      run: python -m pip install build twine
    
    - name: Build
      run: python -m build --sdist

    - name: Check metadata
      run: python -m twine check dist/*

    - uses: actions/upload-artifact@v3
      with:
        path: dist/*.tar.gz


  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
      #  os: [ubuntu-latest, windows-latest, macos-latest]
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: pypa/cibuildwheel@v2.13.0
      env:
        CIBW_ARCHS_MACOS: auto universal2
        CIBW_ARCHS_WINDOWS: auto ARM64
        
    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        path: wheelhouse/*.whl

